import pandas as pd

def opening_stability(df):

    """
    Computes stability for each opening using standard deviation.
    
    Parameter: dataframe 
    """

    df["combined_accuracy"] = (df["mean_white_accuracy"] + df["mean_black_accuracy"]) / 2

    stats = df.groupby(["opening", "eco"])["combined_accuracy"].agg(
        mean_accuracy = "mean",
        stability_std = "std",
        games = "count"
        ).reset_index()

    return stats

# Build prefix dataframe

def build_prefix(df, max_depth = 10):

    """
    For each game, this function generates all partial move sequences (prefixes).
    Example for the move list: ["e2e4", "e7e5", "g1f3"]
    We produce:
    1. ("e2e4")
    2. ("e2e4", "e7e5")
    3. ("e2e4", "e7e5", "g1f3")

    For each prefix the function stores:
    - the prefix itself
    - the game result ("1-0", "0-1", "1/2-1/2")
    - the opening name

    This returns a long dataframe

    """

    rows = []

    for _, row in df.iterrows():
        moves = row["moves"]
        result = row["result"]
        opening = row.get("opening", None)

        if not isinstance(moves, list):
            continue

        depth = min(max_depth, len(moves))

        for p in range(1, depth+1):
            prefix = tuple(moves[:p]) 

            rows.append({
                "prefix": prefix,
                "result": result,
                "opening": opening
            })

    df_prefix = pd.DataFrame(rows)
    return df_prefix


def agg(group):

    """

    Computes aggragated statistics for a given prefix group.

    This function is applied to each group of games that share the same 
    move prefix (generated by build_prefix). For every prefix, it computes:

    - white win rate
    - black win rate
    - draw rate
    - total number of games with that prefix
    - most common opening associated with the prefix

    The output is a pandas series with these summary statistics.

    Parameter: group (of prefix)

    """
    results = group["result"]

    total = len(results)
    white_win = (results == "1-0").sum() / total
    black_win = (results == "0-1").sum() / total
    draw = (results == "1/2-1/2").sum() / total

    # Most common opening for this prefix
    main_opening = group["opening"].mode()

    if len(main_opening) > 0:
        main_opening = main_opening[0]
    else:
        main_opening = None


    return pd.Series({
        "count": total,
        "white_win_rate": round(white_win, 3),
        "black_win_rate": round(black_win, 3),
        "draw_rate": round(draw, 3),
        "main_opening": main_opening
    })
    

def prefix_stats(df, max_depth = 10):
    df_prefix = build_prefix(df, max_depth)
    stats = df_prefix.groupby("prefix").apply(agg).reset_index()
    return stats
